### ISSUE TITLE
Master Mode Problem

### ISSUE THREAD

**Issue by alialbay** [ADElectronics/STM32-FreeModbus-Example#1]
Hi, 

Slave mode works great but while making project for master with Nucleo-F401, similar 13 of building errors have occurred:

Error: L6218E: Undefined symbol eMBRegInputCB (referred from mbfuncinput.o).
Error: L6218E: Undefined symbol vMBPortSerialEnable (referred from mbrtu.o).
Error: L6218E: Undefined symbol vMBPortTimersDisable (referred from mbrtu.o).
Error: L6218E: Undefined symbol vMBPortTimersEnable (referred from mbrtu.o).
Error: L6218E: Undefined symbol xMBPortEventPost (referred from mbrtu.o).
Error: L6218E: Undefined symbol xMBPortSerialGetByte (referred from mbrtu.o).
Error: L6218E: Undefined symbol xMBPortSerialInit (referred from mbrtu.o).
Error: L6218E: Undefined symbol eMBRegDiscreteCB (referred from mbfuncdisc.o).
....

Looking forward to help

**Comment by ADElectronics** [comment]
Hi! I download project, just update path to gcc and compile all fine... maybe you changed makefile or mbconfig.h ?

**Comment by alialbay** [comment]
Hi,
Thank you for reply, i did not change mbconfig.h. When i use STM32 Cube IDE, master program works properly but Keil with ARM compiler gives these errors. Also i changed Keil compiler to GCC and 472 errors are given, probably miss configuration of Keil with GCC.

**Comment by ADElectronics** [comment]
Sorry, i don't know Keil IDE, this example is only to Visual Studio Code + GCC (or you can compile it at console). Maybe need to add project files to compile manually (seems Keil compiler just don't see, where is functions eMBRegInputCB ...).

**Comment by alialbay** [comment]
Thank you for your attention.
